package cmd

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"strconv"
	"strings"

	"github.com/spf13/cobra"

	"mcpscope/internal/store"
)

func init() {
	rootCmd.AddCommand(newReplayCmd())
}

func newReplayCmd() *cobra.Command {
	var inputPath string
	var server string
	var transport string

	cmd := &cobra.Command{
		Use:   "replay [command...]",
		Short: "Replay exported traces against an MCP server",
		RunE: func(cmd *cobra.Command, args []string) error {
			if strings.TrimSpace(inputPath) == "" {
				return fmt.Errorf("--input is required")
			}

			data, err := os.ReadFile(inputPath)
			if err != nil {
				return fmt.Errorf("read replay input: %w", err)
			}

			var traces []store.Trace
			if err := json.Unmarshal(data, &traces); err != nil {
				return fmt.Errorf("decode replay input: %w", err)
			}

			switch normalized, err := validateTransport(transport); {
			case err != nil:
				return err
			case normalized == "http":
				target := strings.TrimSpace(server)
				if target == "" && len(args) > 0 {
					target = args[0]
				}
				return replayHTTP(cmd.Context(), target, traces)
			default:
				command := commandFromInputs(strings.TrimSpace(server), args)
				if len(command) == 0 {
					return fmt.Errorf("provide --server or a command after `--`")
				}
				return replayStdio(cmd.Context(), command, traces)
			}
		},
	}

	cmd.Flags().StringVar(&inputPath, "input", "", "Path to a JSON trace export generated by `mcpscope export`")
	cmd.Flags().StringVar(&server, "server", "", "Target MCP server command or HTTP URL")
	cmd.Flags().StringVar(&transport, "transport", "stdio", "Replay transport: stdio or http")

	return cmd
}

func replayHTTP(ctx context.Context, target string, traces []store.Trace) error {
	if target == "" {
		return fmt.Errorf("missing replay target URL")
	}

	client := &http.Client{}
	for i, trace := range traces {
		if trace.Method == "" {
			continue
		}
		payload, err := json.Marshal(map[string]any{
			"jsonrpc": "2.0",
			"id":      i + 1,
			"method":  trace.Method,
			"params":  json.RawMessage(trace.ParamsPayload),
		})
		if err != nil {
			return err
		}
		req, err := http.NewRequestWithContext(ctx, http.MethodPost, target, bytes.NewReader(payload))
		if err != nil {
			return err
		}
		req.Header.Set("Content-Type", "application/json")
		resp, err := client.Do(req)
		if err != nil {
			return err
		}
		io.Copy(io.Discard, resp.Body)
		resp.Body.Close()
	}
	return nil
}

func replayStdio(ctx context.Context, command []string, traces []store.Trace) error {
	cmd := exec.CommandContext(ctx, command[0], command[1:]...)
	stdin, err := cmd.StdinPipe()
	if err != nil {
		return err
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return err
	}
	cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil {
		return err
	}

	reader := bufio.NewReader(stdout)
	for i, trace := range traces {
		if trace.Method == "" {
			continue
		}
		payload, err := json.Marshal(map[string]any{
			"jsonrpc": "2.0",
			"id":      i + 1,
			"method":  trace.Method,
			"params":  json.RawMessage(trace.ParamsPayload),
		})
		if err != nil {
			return err
		}
		if _, err := fmt.Fprintf(stdin, "Content-Length: %d\r\n\r\n", len(payload)); err != nil {
			return err
		}
		if _, err := stdin.Write(payload); err != nil {
			return err
		}
		if _, err := readReplayFrame(reader); err != nil {
			return err
		}
	}

	stdin.Close()
	return cmd.Wait()
}

func readReplayFrame(reader *bufio.Reader) ([]byte, error) {
	contentLength := -1
	for {
		line, err := reader.ReadString('\n')
		if err != nil {
			return nil, err
		}
		trimmed := strings.TrimRight(line, "\r\n")
		if trimmed == "" {
			break
		}
		name, value, found := strings.Cut(trimmed, ":")
		if found && strings.EqualFold(strings.TrimSpace(name), "Content-Length") {
			contentLength, err = strconv.Atoi(strings.TrimSpace(value))
			if err != nil {
				return nil, err
			}
		}
	}
	if contentLength < 0 {
		return nil, fmt.Errorf("missing Content-Length header")
	}
	payload := make([]byte, contentLength)
	_, err := io.ReadFull(reader, payload)
	return payload, err
}
